### PR TITLE
PostgreSQL installation on stretch

### PR DESCRIPTION
**Pull request by madtibo**
* remove duplicated queries + run query as postgres in _common.sh
We will use the existing functions from the [psql yunohost helper](https://github.com/YunoHost/yunohost/blob/stretch-stable/data/helpers.d/psql).

  * Install PG postgis extension package and correct database creation/deletion

  * correct database backup / restore

### CODE REVIEW

**Comment by alexAubin** [comment]
Bump, any feedback on this ? Current maintainer seem to be @frju365 since cyp is probably inactive ?

**Comment by zicmama** [comment]
I have tried to install umap from your fork.
 This is the error I get

> sudo yunohost app install https://github.com/madtibo/umap_ynh.git
> 
>   File "/usr/bin/yunohost", line 213, in <module>
>     timeout=opts.timeout,
>   File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 136, in cli
>     moulinette.run(args, output_as=output_as, password=password, timeout=timeout)
>   File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 390, in run
>     ret = self.actionsmap.process(args, timeout=timeout)
>   File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 498, in process
>     return func(**arguments)
>   File "/usr/lib/moulinette/yunohost/app.py", line 728, in app_install
>     args_odict = _parse_args_from_manifest(manifest, 'install', args=args_dict, auth=auth)
>   File "/usr/lib/moulinette/yunohost/app.py", line 2034, in _parse_args_from_manifest
>     return _parse_action_args_in_yunohost_format(args, action_args, auth)
>   File "/usr/lib/moulinette/yunohost/app.py", line 2204, in _parse_action_args_in_yunohost_format
>     raise MoulinetteError(errno.EINVAL, m18n.n('app_location_unavailable', "\n".join(apps=apps)))
> TypeError: join() takes no keyword arguments
>

**Comment by madtibo** [comment]
@zicmama I have no idea about your error. It seems very yunohost related. Are you using the right version of yunohost (stretch)?
Second thing, I doubt that your line of install will work. I think you will be using the master branch from my repo. The fix is in the issue_13 branch. You would have to download the project and install it using the application path on your server.

**Comment by frju365** [comment]
Well, let's merge and see. Anyway, the package doesn't work for instance and the maintainer (me) hadn't time to test the PR :P

**Pull request merged**
